name: Update Lifetime Contributions
on:
  schedule:
    - cron: "15 3 * * *"  # daily 03:15 UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip requests
      - name: Run contribution updater
        env:
          GH_LIFETIME_TOKEN: ${{ secrets.GH_LIFETIME_TOKEN }}
        run: |
          python scripts/update_contribs.py
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update lifetime contributions"
            git push
          else
            echo "No changes to commit."
